name: Generate Gallery JS

on:
  push:
    paths:
      - 'images/**'

jobs:
  generate-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate JS for boat folder
        run: |
          echo "const boatFiles = [" > boatFiles.js
          for f in images/boat/*; do
            echo "  \"$f\"," >> boatFiles.js
          done
          echo "];" >> boatFiles.js

      - name: Generate JS for Aurelia folder
        run: |
          echo "const aureliaFiles = [" > aureliaFiles.js
          for f in images/Aurelia/*; do
            echo "  \"$f\"," >> aureliaFiles.js
          done
          echo "];" >> aureliaFiles.js

      - name: Commit JS updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add boatFiles.js aureliaFiles.js
          git commit -m "Auto-update gallery arrays" || echo "No changes to commit"
          git push
