name: Auto-Inject Galleries

on:
  push:
    paths:
      - 'images/**'
      - '.github/workflows/generate-gallery.yml'
      - 'index.html'

permissions: write-all

jobs:
  inject-galleries:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Generate Boat Gallery HTML
      - name: Generate Boat Gallery HTML
        run: |
          echo "<div class='gallery'>" > boat.tmp
          for img in images/boat/*; do
            if [[ "$img" =~ \.(jpg|jpeg|png|gif|webp|mp4|mov|JPG|JPEG|PNG|GIF|WEBP|MP4|MOV)$ ]]; then
              echo "<a href='$img' target='_blank'><img src='$img' alt='Boat image'></a>" >> boat.tmp
            fi
          done
          echo "</div>" >> boat.tmp

      # ✅ Generate Aurelia Gallery HTML
      - name: Generate Aurelia Gallery HTML
        run: |
          echo "<div class='gallery'>" > aurelia.tmp
          for img in images/Aurelia/*; do
            if [[ "$img" =~ \.(jpg|jpeg|png|gif|webp|mp4|mov|JPG|JPEG|PNG|GIF|WEBP|MP4|MOV)$ ]]; then
              echo "<a href='$img' target='_blank'><img src='$img' alt='Aurelia image'></a>" >> aurelia.tmp
            fi
          done
          echo "</div>" >> aurelia.tmp

      # ✅ Inject galleries into index.html
      - name: Inject galleries into index.html
        run: |
          # Replace Boat gallery section
          awk '/<div id="boat-gallery">/{print;system("cat boat.tmp");next}1' index.html > index_new.html
          mv index_new.html index.html

          # Replace Aurelia gallery section
          awk '/<div id="aurelia-gallery">/{print;system("cat aurelia.tmp");next}1' index.html > index_new.html
          mv index_new.html index.html

      # ✅ Commit and Push changes with PAT
      - name: Commit and Push using PAT
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "Auto Gallery Bot"
          git config user.email "phmann-bot@example.com"
          git add index.html
          git commit -m "Auto-inject Boat and Aurelia galleries" || echo "No changes to commit"

          # Push using Personal Access Token (PAT)
          REPO="github.com/phillipmann6813/phillipmann6813.github.io.git"
          git push https://${GH_PAT}@${REPO} HEAD:main
